cfg:
  learn_alignment: true
  bin_loss_warmup_epochs: 100
  n_speakers: 1
  max_token_duration: 75
  symbols_embedding_dim: 384
  pitch_embedding_kernel_size: 3
  pitch_fmin: 65.40639132514966
  pitch_fmax: 2093.004522404789
  pitch_mean: 121.9
  pitch_std: 23.1
  sample_rate: 22050
  n_mel_channels: 80
  n_window_size: 1024
  n_window_stride: 256
  n_fft: 1024
  lowfreq: 0
  highfreq: 8000
  window: hann
  text_normalizer:
    _target_: nemo_text_processing.text_normalization.normalize.Normalizer
    lang: en
    input_case: cased
    whitelist: /Users/euna/Desktop/KU/WorkSpace/NeMo-FastPitch/scripts/tts_dataset_files/lj_speech.tsv
  text_normalizer_call_kwargs:
    verbose: false
    punct_pre_process: true
    punct_post_process: true
  text_tokenizer:
    add_blank_at: true
    _target_: nemo.collections.common.tokenizers.text_to_speech.tts_tokenizers.EnglishPhonemesTokenizer
    punct: true
    stresses: true
    chars: true
    apostrophe: true
    pad_with_space: true
    g2p:
      _target_: nemo_text_processing.g2p.modules.EnglishG2p
      phoneme_dict: /Users/euna/Desktop/KU/WorkSpace/NeMo-FastPitch/scripts/tts_dataset_files/cmudict-0.7b_nv22.10
      heteronyms: /Users/euna/Desktop/KU/WorkSpace/NeMo-FastPitch/scripts/tts_dataset_files/heteronyms-052722
      phoneme_probability: 0.5
  train_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.TTSDataset
      manifest_filepath: /Users/euna/Desktop/KU/WorkSpace/NeMo-FastPitch/6097_manifest_train_dur_5_mins_local.json
      sample_rate: 22050
      sup_data_path: ./fastpitch_sup_data
      sup_data_types:
      - align_prior_matrix
      - pitch
      n_fft: 1024
      win_length: 1024
      hop_length: 256
      window: hann
      n_mels: 80
      lowfreq: 0
      highfreq: 8000
      max_duration: null
      min_duration: 0.1
      ignore_file: null
      trim: false
      pitch_fmin: 30
      pitch_fmax: 512
      pitch_norm: true
      pitch_mean: 121.9
      pitch_std: 23.1
      use_beta_binomial_interpolator: true
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 24
      num_workers: 12
      pin_memory: true
  validation_ds:
    dataset:
      _target_: nemo.collections.tts.torch.data.TTSDataset
      manifest_filepath: /Users/euna/Desktop/KU/WorkSpace/NeMo-FastPitch/6097_manifest_train_dur_5_mins_local.json
      sample_rate: 22050
      sup_data_path: ./fastpitch_sup_data
      sup_data_types:
      - align_prior_matrix
      - pitch
      n_fft: 1024
      win_length: 1024
      hop_length: 256
      window: hann
      n_mels: 80
      lowfreq: 0
      highfreq: 8000
      max_duration: null
      min_duration: null
      ignore_file: null
      trim: false
      pitch_fmin: 65.40639132514966
      pitch_fmax: 2093.004522404789
      pitch_norm: true
      pitch_mean: 121.9
      pitch_std: 23.1
      use_beta_binomial_interpolator: true
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 24
      num_workers: 8
      pin_memory: true
  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    features: 80
    lowfreq: 0
    highfreq: 8000
    n_fft: 1024
    n_window_size: 1024
    window_size: false
    n_window_stride: 256
    window_stride: false
    pad_to: 1
    pad_value: 0
    sample_rate: 22050
    window: hann
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: add
    log_zero_guard_value: 1.0e-05
    mag_power: 1.0
  input_fft:
    _target_: nemo.collections.tts.modules.transformer.FFTransformerEncoder
    n_layer: 6
    n_head: 1
    d_model: 384
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0
    d_embed: 384
  output_fft:
    _target_: nemo.collections.tts.modules.transformer.FFTransformerDecoder
    n_layer: 6
    n_head: 1
    d_model: 384
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0
  alignment_module:
    _target_: nemo.collections.tts.modules.aligner.AlignmentEncoder
    n_text_channels: 384
  duration_predictor:
    _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
    input_size: 384
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 2
  pitch_predictor:
    _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
    input_size: 384
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 2
  optim:
    name: adam
    lr: 0.0002
    betas:
    - 0.9
    - 0.999
    weight_decay: 1.0e-06
  target: nemo.collections.tts.models.fastpitch.FastPitchModel
  nemo_version: 1.13.0rc0
